### PR TITLE
Fix image URLs

### PR DESCRIPTION
**Pull request by steadysupply**
These tutorials look great. Did a bit of URL linting `:)`

### CODE REVIEW

**Comment by steadysupply** [comment]
Oh yeah I added a `docker-compose` file to contain deps too

**Comment by spanndemic** [comment]
Awesome, thank you for the help!

One question, though - and forgive me for not being more familiar with Docker setup... does Docker require a separate Readme.md? Or could those lines be added to the main readme instead of linking?

**Comment by steadysupply** [comment]
Nope, neither Docker or `docker-compose` depend on the readme. I'll get rid of it and put the few lines from there in the existing readme.

**Comment by spanndemic** [comment]
That would be great! or I can do it after the merge, either way.

**Comment by steadysupply** [comment]
There we are. I also ran through the relevant parts of the "Hello World" tutorial on Ubuntu and it worked like a charm.

**Comment by spanndemic** [comment]
👍  awesome, thanks again!

**Pull request merged**
